baseURL = 'https://blog.geosalib.com/'
languageCode = 'en-us'
title = 'Geo Salib | Me & My Thoughts!'
theme = 'mana'
summaryLength = '20'

[params]
  description = "This is a collection of my thoughts, projects, and anything else...It's Me!"
  favicon = "https://blog.geosalib.com/favicon.ico"
  footerText = "Love, for Love is God, and God is Good."  # Optional
  
  # Hero section title (optional - defaults to site.Title)
  heroTitleLine1 = "Geo Salib"  # First line of hero title
  heroTitleLine2 = "suffering and enjoying the human condition"    # Second line of hero title (optional)
  
  [params.avatar]
  url = "https://blog.geosalib.com/avatar.png"

  [params.social]
  github = "https://github.com/Geo-sudo"
  linkedin = "https://linkedin.com/in/geo-sudo/"
  email = "george.nady.contact@gmail.com"

  [[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'Theology'
		pageRef = '/tags/Theology'
		weight = 15
	[[menu.main]]
		name = 'Astrophysics'
		pageRef = '/tags/astrophysics'
		weight = 20
	[[menu.main]]
		name = 'Poetry'
		pageRef = '/tags/poetry'
		weight = 25
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 30
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 35

[pagination]
  pageSize = 10

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.parser]
      # Enable block-level attributes for blockquotes
      [markup.goldmark.parser.attribute]
        block = true
        title = true

[params.copyright]
  startYear = 2023
  owner = "George Salib"

  [params.buyMeACoffee]
  enabled = true
  id = "geo.sudo"
  description = "Help fund my toxic addiction to caffeine!"
  message = ""  # Optional message
  color = "#BD5FFF"  # Widget color
  position = "Right"  # "Left" or "Right"
  x_margin = "18"  # Horizontal margin in pixels
  y_margin = "18"  # Vertical margin in pixels

[module]
  [module.hugoVersion]
    extended = true
    min = "0.100.0"